version: "3.9"
services:
  test:
    image: "exercise-1"
    volumes:
      - .:/app
    command: python -m pytest
  run:
    image: "exercise-1"
    volumes:
      - .:/app
    command: python main.py